version: "{build}"

branches:

  only:

  - master

clone_depth: 1

build: false

environment:
    DEBUG: True
    REDIRECT_URIS: http://test.example.com:8000/api/pulse/oauth2callback
    SSL_PROTECTION: False
    DATABASE_URL: postgres://postgres:Password12!@localhost:5432/pulseapi
    SECRET_KEY: BetPHpGoUXUwjaAXm6ArIhV95xLdDZtu8QEGnNXY3eTknIkD

    matrix:
      - PYTHON: "C:\\Python36"
        PYTHON_VERSION: "3.6.4"
        PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PYTHONPATH=%APPVEYOR_BUILD_FOLDER%"
  - "python -m pip install --upgrade pip"
  - "python -m pip install pipenv"
  - "python -m pipenv install --dev"

services:
  - postgresql

before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - createdb pulseapi
  - "python -m pipenv run manage.py migrate"

test_script:
  - "python -m pipenv run flake8 pulseapi --config=./pulseapi/tox.ini --ignore=E722"
  - "python -m pipenv run python manage.py test"

cache:
  - "%LOCALAPPDATA%\\pip\\Cache"
