version: "{build}"

branches:

  only:

  - master

clone_depth: 1

build: false

environment:
    DEBUG: True
    REDIRECT_URIS: http://test.example.com:8000/api/pulse/oauth2callback
    SSL_PROTECTION: False
    DATABASE_URL: postgres://postgres:Password12!@localhost:5432/pulseapi
    SECRET_KEY: BetPHpGoUXUwjaAXm6ArIhV95xLdDZtu8QEGnNXY3eTknIkD

    matrix:
      - PYTHON: "C:\\Python36"
        PYTHON_VERSION: "3.6.1"
        PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "virtualenv pulseapi -p %PYTHON%/python.exe"
  - "./pulseapi/Scripts/activate"
  - "python -m pip install --upgrade pip"
  - "pip install -r requirements.txt"

services:
  - postgresql

before_test:
  - "./pulseapi/Scripts/activate"
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - createdb pulseapi
  - python manage.py migrate

test_script:
  - "./pulseapi/Scripts/activate"
  - "python manage.py test"

cache:
  - "%LOCALAPPDATA%\\pip\\Cache"
